feat: Backlog/align utils
ftrackhq/ftrack-connect-pipeline-maya pull request #6
Opened 2023-02-27 16:54 UTC by henriknorin-ftrack

Resolves : 

* CLICKUP-865bugxcq

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [ ] The PR contains update to the release notes.
- [X] The PR contains update to the documentation.

This PR has been tested on :

- [ ] Windows.
- [X] MacOs, Maya 2022 & 2023
- [ ] Linux.

## Changes

Split utils across DCCs to align with Unreal

## Test

Do a full cycle test in Maya

2023-03-01 11:46 UTC, lluisCM requested changes
Please test it first and I'll review later.

2023-03-01 11:46 UTC, lluisCM commented on resource/bootstrap/userSetup.py
> -import maya.utils
Can't remove this as it's used

2023-03-01 11:46 UTC, lluisCM commented on source/ftrack_connect_pipeline_maya/client/asset_manager.py
> -from ftrack_connect_pipeline_maya.utils.custom_commands import get_main_window
Is this not used anywhere?

2023-03-01 11:46 UTC, lluisCM commented on source/ftrack_connect_pipeline_maya/client/change_context.py
> -from ftrack_connect_pipeline_maya.utils.custom_commands import init_maya
You are missing the import

2023-03-01 11:59 UTC, henriknorin-ftrack commented on source/ftrack_connect_pipeline_maya/client/asset_manager.py
> -from ftrack_connect_pipeline_maya.utils.custom_commands import get_main_window
No import is not used anymore, was there during a phase when I were debugging window modality in Maya

2023-03-01 12:01 UTC, henriknorin-ftrack commented on source/ftrack_connect_pipeline_maya/client/change_context.py
> -from ftrack_connect_pipeline_maya.utils.custom_commands import init_maya
Well spotted, fixing

2023-03-01 12:03 UTC, henriknorin-ftrack commented on resource/bootstrap/userSetup.py
> -import maya.utils
Import is not used anywere in code, only explicit through maya.utils.MayaGuiLogHandler but that does not need the import right?

2023-03-10 13:37 UTC, lluisCM approved these changes
LGTM

2023-03-13 09:37 UTC, merged